### ISSUE TITLE
Selecting any signature type returns null

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-signature/GroupDocs.Signature-for-Java-Spring#29]
When we select any signature type from the L.H.S panel, the error popup appears containing "null". Please see [this](https://imgur.com/G17fqAh) screenshot for reference. The error can also be viewed in the browser's console. Regards

This issue is also reported in [https://forum.groupdocs.com/t/how-to-test-digital-signature-using-ui-spring-application/7214/8](https://forum.groupdocs.com/t/how-to-test-digital-signature-using-ui-spring-application/7214/8).

**Comment by koleslena** [comment]
@usmanazizgroupdocs Hi! Could you verify that in your file directory specified in the configuration file there is a DocumentSamples folder, does it have such a structure http://prntscr.com/njz5zv ?

**Comment by usmanazizgroupdocs** [comment]
@koleslena 

> does it have such a structure http://prntscr.com/njz5zv ?

No, the _DocumentSamples_ folder doesn't contain the subfolders that are in your provided screenshot.

**Comment by koleslena** [comment]
@usmanazizgroupdocs Thanks for your reply. The fix for the problem was merged. Please, pull the lastest version and check. Waiting for your feedback.

**Comment by usmanazizgroupdocs** [comment]
@koleslena I am getting the same issue in the latest version as well and the folders in _DocumentSamples_ are not being created. The issue resolves if I manually create the folders. Regards

**Comment by koleslena** [comment]
Hi @usmanazizgroupdocs, I found the cause of this problem and fixed it. Folders should now be created without problems.

**Comment by usmanazizgroupdocs** [comment]
@koleslena I have verified the fix and the issue is resolved now. Thanks

**Comment by koleslena** [comment]
@usmanazizgroupdocs thank you for the reply
