### ISSUE TITLE
Option to add signature to all pages in one go

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-signature/GroupDocs.Signature-for-Java-Spring#32]
This feature is requested via forum topic: [https://forum.groupdocs.com/t/group-docs-signature-ui-application-issue/7335](https://forum.groupdocs.com/t/group-docs-signature-ui-application-issue/7335)

The user has requested the option to add the signature to all pages of the document in one go instead of adding to each page one by one manually.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Are there any updates regarding the implementation of this feature?

**Comment by egorovpavel** [comment]
Hi @usmanazizgroupdocs, we plan to start working on this feature next week.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Is there any progress updates on this feature?

**Comment by koleslena** [comment]
Hi @usmanazizgroupdocs , the feature was developed and is under testing currently.

**Comment by egorovpavel** [comment]
@usmanazizgroupdocs we implemented this feature in the latest angular version GroupDocs.Signature UI.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Thanks for informing.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Could you please share the commit details in which this feature is added?
