### ISSUE TITLE
Amend GroupDocs Angular code

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-signature/GroupDocs.Signature-for-Java-Spring#39]
This issue is raised in https://forum.groupdocs.com/t/digital-signature-spring-java-application-compatibility-with-internet-explorer/7898/4
Hi,
One of the user developed his own Angular application but wants to add GroupDocs Angular code node_modules@groupdocs.examples.angular and amend it. Can you please share a way or steps to customize the code? 
Thanks

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

I apologise for the delay, see if this [example](https://gist.github.com/bobkovalex/0674e7d7c54a54daf01a37927df27b05) works for you.
Thanks.
